#!/bin/sh
# Setup a machine for MailMate
set -x

echo "Installing MailMate"

DOTFILES_ROOT="`pwd`"

mailmate_dir=~/Library/Application\ Support/MailMate

if [ -d "$mailmate_dir/Resources" ]; then
	mv "$mailmate_dir/Resources" "$mailmate_dir/Resources.backup"
fi
ln -s "$DOTFILES_ROOT/mailmate/Resources" "$mailmate_dir"